### PR TITLE
rename type variables

### PR DESCRIPTION
**Pull request by soenkehahn**
This PR just renames a bunch of type variables.

Personally I never quite understood why best practices around variable names seem to not be applied to type parameters. Specifically, I think it's good to:

- avoid abbreviations and
- stick to conventions like camelCase that are used everywhere else in the code.

I hope I guessed all the names correctly given the abbreviations. Also `GetVisitorResult` seems long. What do people think?

### CODE REVIEW

**Comment by astampoulis** [comment]
@soenkehahn I like the rename, but I do agree that `GetVisitorResult` is too long. I haven't had an idea yet, but I'd like us to figure that out before merging. Question: do you think that having `Get` in the type variable name is better than having a postfix `F`? For me using that kind of a name is quite conventional, but I am not sure where I'm getting that convention from :smile:

**Comment by astampoulis** [comment]
Actually after talking more about #41, I think what I suggested above is not needed yet. It'll be necessary I think once we work on `NumberRep`, but that will be part of a separate PR.

**Comment by sleexyz** [comment]
I'm fine with all of the new variable names, with maybe the exception of `GetVisitorResult`.

Can we call `GetVisitorResult` something short like `F`, or `V`, because the whole thing is hack to encode HKT's anyways? I feel like short variable names are more revealing of the mechanics of these type level hacks than these "semantic" names.

Also, `$Call<F, Input>` is more IMO more readable than `$Call<GetVisitorResult, Input>` in a function signature just because of the sheer size of `GetVisitorResult`

**Comment by soenkehahn** [comment]
I'll change `GetVisitorResult` to `F` and then merge. @sleexyz, @astampoulis: any objections?

**Comment by sleexyz** [comment]
sounds good

**Comment by astampoulis** [comment]
@soenkehahn That sounds good to me too! :+1:

**Pull request merged**
